DROP TABLE IF EXISTS PORTFOLIO;

CREATE TABLE PORTFOLIO( ID int AUTO_INCREMENT PRIMARY KEY NOT NULL , CODE char(10) UNIQUE, AMOUNT int, DEVISE enum('NONE','EURO','DOLLAR'), MANAGER varchar(20));

INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000001',5702,'DOLLAR','Baptiste');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000002',9552,'EURO','Baptiste');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000003',7698,'EURO','Baptiste');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000004',7334,'DOLLAR','Baptiste');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000005',7034,'DOLLAR','Baptiste');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000006',6724,'EURO','Antoine');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000007',9606,'EURO','Antoine');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000008',9904,'DOLLAR','Baptiste');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000009',6392,'DOLLAR','Antoine');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000010',8147,'EURO','Antoine');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000011',9806,'DOLLAR','Antoine');
INSERT INTO PORTFOLIO (CODE,AMOUNT,DEVISE,MANAGER) VALUES ('PTF0000012',9861,'DOLLAR','Baptiste');